logging:
  level:
    org.springframework: DEBUG

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: demo_route
          uri: lb://app-demo
          order: 0
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1