logging:
  level:
    org.springframework: DEBUG

server:
  port: 18000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: app-server
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: zhaodongDB888
