logging:
  level:
    org.springframework: DEBUG

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: app-demo
  security:
    oauth2:
      jwt:
        signingKey: zhaodongDB888

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/demo_user?useSSL=false
    username: ${MYSQL_ROOT_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300

  mail:
    host: mail.onjdcloud.com
    port: 465
    protocol: smtp
    username: helun@zhaodongdb.com
    password: wskwwx,20190408
    properties:
      mail:
        smtp:
          ssl:
            enable: true

soa:
  path: /user

jwt:
  secret: zhaodongDB888
  access_token:
    expiration: 600
  refresh_token:
    expiration: 300
