logging:
  level:
    org.springframework: DEBUG

server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/user_center?useSSL=false
    username: ${MYSQL_ROOT_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      jwt:
        signingKey: zhaodongDB888
